### ISSUE TITLE
MAPA MENTAL

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/actividad-4-mapa-mental-calidad-de-software-Sandra631#1]
[MAPA MENTAL_GESTION DE CALIDAD.pdf](https://github.com/user-attachments/files/17071745/MAPA.MENTAL_GESTION.DE.CALIDAD.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18...Bien hecho y revisado...
